apiVersion: v1
kind: Secret
metadata:
  namespace: ssilalak
  name: mongodb-secret
  labels:
    app: mongodb
type: Opaque
stringData:
  mongodb-username: user
  mongodb-password: password

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ssilalak
  name: mongodb-configmap
data:
  database_url: mongodb-service